### ISSUE TITLE
Calling function fails with cannot find 'matched' module

### ISSUE THREAD

**Issue by bobbygryzynger** [jonschlinkert/delete-empty#7] opened 2016-11-14 05:55 UTC
Running `deleteEmpty.sync('/mydir')` is resulting in the following error output for me:
```
Error: Cannot find module 'matched'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Function.getter [as glob] (/Users/robertgryzynger/Sites/Meyers8/deploy/docroot/themes/custom/meyers/node_modules/lazy-cache/index.js:34:42)
    at Function.deleteEmpty.sync (/Users/robertgryzynger/Sites/Meyers8/deploy/docroot/themes/custom/meyers/node_modules/delete-empty/index.js:58:19)
    at /Users/robertgryzynger/Sites/Meyers8/deploy/docroot/themes/custom/meyers/gulpfile.js:119:18
    at taskWrapper (/Users/robertgryzynger/Sites/Meyers8/deploy/docroot/themes/custom/meyers/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
```
I'm using what appears to be the latest version: `0.1.3`.

**Comment by jonschlinkert** [comment] 2016-11-14 06:34
did you try deleting `node_modules` and reinstalling everything?

**Comment by bobbygryzynger** [comment] 2016-11-14 14:32
@jonschlinkert - yeah, I tried removing and reinstalling, still received the same error output.

**Comment by jonschlinkert** [comment] 2016-12-10 10:05
I can't reproduce. Closing since this seems unrelated to this library given that the package you're referring to is obviously listed as a dependency in package.json. If you're still having this issue, please provide example code, OS and any other information that might be pertinent.

**Closed as completed by jonschlinkert** 2016-12-10 10:05 UTC
